title: Hi, I am Louis Carpentier
theme: minima

include:
  - _pages

author:
  name: "Louis Carpentier"
  avatar: "https://github.com/LouisCarpentier42.png"
  bio: "PhD researcher in Computer Science at DTAI (KU Leuven, Belgium)"
  location: "Bruges, Belgium"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:louis.carpentier@kuleuven.be"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/carpentierlouis/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/LouisCarpentier42"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=85qn38YAAAAJ"
    - label: "0000-0002-3679-8873"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-3679-8873"
